/*Copyright 2026 Fraunhofer-Gesellschaft zur Förderung der angewandten Forschung e.V. and Universität Stuttgart

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.*/


// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const DataTypeCreateSchema = {
    properties: {
        expanded_node_id: {
            type: 'string',
            title: 'Expanded Node Id'
        },
        display_name: {
            type: 'string',
            title: 'Display Name'
        },
        definition: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Definition'
        },
        definition_vector: {
            anyOf: [
                {
                    items: {
                        type: 'number'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Definition Vector'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        description_vector: {
            anyOf: [
                {
                    items: {
                        type: 'number'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description Vector'
        },
        documentation: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Documentation'
        },
        id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        is_abstract: {
            type: 'boolean',
            title: 'Is Abstract'
        },
        spec_id: {
            type: 'integer',
            title: 'Spec Id'
        }
    },
    type: 'object',
    required: ['expanded_node_id', 'display_name', 'definition', 'description', 'documentation', 'is_abstract', 'spec_id'],
    title: 'DataTypeCreate'
} as const;

export const DataTypePublicSchema = {
    properties: {
        create_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Create Time'
        },
        update_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Update Time'
        },
        expanded_node_id: {
            type: 'string',
            title: 'Expanded Node Id'
        },
        display_name: {
            type: 'string',
            title: 'Display Name'
        },
        definition: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Definition'
        },
        definition_vector: {
            anyOf: [
                {
                    items: {
                        type: 'number'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Definition Vector'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        description_vector: {
            anyOf: [
                {
                    items: {
                        type: 'number'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description Vector'
        },
        documentation: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Documentation'
        },
        id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        is_abstract: {
            type: 'boolean',
            title: 'Is Abstract'
        },
        spec_id: {
            type: 'integer',
            title: 'Spec Id'
        },
        spec: {
            '$ref': '#/components/schemas/SpecPublic'
        }
    },
    type: 'object',
    required: ['expanded_node_id', 'display_name', 'definition', 'description', 'documentation', 'is_abstract', 'spec_id', 'spec'],
    title: 'DataTypePublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const ModellingRuleEnumSchema = {
    type: 'string',
    enum: ['M', 'O', 'MP', 'OP'],
    title: 'ModellingRuleEnum'
} as const;

export const ModellingRulePublicSchema = {
    properties: {
        create_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Create Time'
        },
        update_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Update Time'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        rule: {
            '$ref': '#/components/schemas/ModellingRuleEnum'
        }
    },
    type: 'object',
    required: ['id', 'rule'],
    title: 'ModellingRulePublic'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const NodeCreateSchema = {
    properties: {
        expanded_node_id: {
            type: 'string',
            title: 'Expanded Node Id'
        },
        display_name: {
            type: 'string',
            title: 'Display Name'
        },
        definition: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Definition'
        },
        definition_vector: {
            anyOf: [
                {
                    items: {
                        type: 'number'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Definition Vector'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        description_vector: {
            anyOf: [
                {
                    items: {
                        type: 'number'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description Vector'
        },
        documentation: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Documentation'
        },
        node_type_id: {
            type: 'integer',
            title: 'Node Type Id'
        },
        spec_id: {
            type: 'integer',
            title: 'Spec Id'
        },
        typedefinition_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Typedefinition Id'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        example_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Example Id'
        },
        data_type_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Type Id'
        },
        unit_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Unit Id'
        },
        modelling_rule_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Modelling Rule Id'
        },
        naming_example: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Naming Example'
        },
        is_abstract: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Abstract'
        }
    },
    type: 'object',
    required: ['expanded_node_id', 'display_name', 'definition', 'description', 'documentation', 'node_type_id', 'spec_id', 'parent_id'],
    title: 'NodeCreate'
} as const;

export const NodePublicSchema = {
    properties: {
        create_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Create Time'
        },
        update_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Update Time'
        },
        expanded_node_id: {
            type: 'string',
            title: 'Expanded Node Id'
        },
        display_name: {
            type: 'string',
            title: 'Display Name'
        },
        definition: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Definition'
        },
        definition_vector: {
            anyOf: [
                {
                    items: {
                        type: 'number'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Definition Vector'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        description_vector: {
            anyOf: [
                {
                    items: {
                        type: 'number'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description Vector'
        },
        documentation: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Documentation'
        },
        node_type_id: {
            type: 'integer',
            title: 'Node Type Id'
        },
        spec_id: {
            type: 'integer',
            title: 'Spec Id'
        },
        typedefinition_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Typedefinition Id'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        example_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Example Id'
        },
        data_type_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Type Id'
        },
        unit_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Unit Id'
        },
        modelling_rule_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Modelling Rule Id'
        },
        naming_example: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Naming Example'
        },
        is_abstract: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Abstract'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        node_type: {
            '$ref': '#/components/schemas/NodeTypePublic'
        },
        spec: {
            '$ref': '#/components/schemas/SpecPublic'
        },
        parent: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/NodePublicReference'
                },
                {
                    type: 'null'
                }
            ]
        },
        typedefinition: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/NodePublicReference'
                },
                {
                    type: 'null'
                }
            ]
        },
        data_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/DataTypePublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        unit: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/UnitPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        modelling_rule: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ModellingRulePublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['expanded_node_id', 'display_name', 'definition', 'description', 'documentation', 'node_type_id', 'spec_id', 'parent_id', 'id', 'node_type', 'spec', 'parent', 'typedefinition', 'data_type', 'unit', 'modelling_rule'],
    title: 'NodePublic'
} as const;

export const NodePublicReferenceSchema = {
    properties: {
        create_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Create Time'
        },
        update_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Update Time'
        },
        expanded_node_id: {
            type: 'string',
            title: 'Expanded Node Id'
        },
        display_name: {
            type: 'string',
            title: 'Display Name'
        },
        definition: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Definition'
        },
        definition_vector: {
            anyOf: [
                {
                    items: {
                        type: 'number'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Definition Vector'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        description_vector: {
            anyOf: [
                {
                    items: {
                        type: 'number'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description Vector'
        },
        documentation: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Documentation'
        },
        node_type_id: {
            type: 'integer',
            title: 'Node Type Id'
        },
        spec_id: {
            type: 'integer',
            title: 'Spec Id'
        },
        typedefinition_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Typedefinition Id'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        example_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Example Id'
        },
        data_type_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Type Id'
        },
        unit_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Unit Id'
        },
        modelling_rule_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Modelling Rule Id'
        },
        naming_example: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Naming Example'
        },
        is_abstract: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Abstract'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        node_type: {
            '$ref': '#/components/schemas/NodeTypePublic'
        },
        spec: {
            '$ref': '#/components/schemas/SpecPublic'
        },
        data_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/DataTypePublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        unit: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/UnitPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        modelling_rule: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ModellingRulePublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['expanded_node_id', 'display_name', 'definition', 'description', 'documentation', 'node_type_id', 'spec_id', 'parent_id', 'id', 'node_type', 'spec', 'data_type', 'unit', 'modelling_rule'],
    title: 'NodePublicReference'
} as const;

export const NodeSemSearchSchema = {
    properties: {
        node: {
            '$ref': '#/components/schemas/NodePublic'
        },
        similarity: {
            type: 'number',
            title: 'Similarity'
        }
    },
    type: 'object',
    required: ['node', 'similarity'],
    title: 'NodeSemSearch'
} as const;

export const NodeTypeEnumSchema = {
    type: 'string',
    enum: ['Variable', 'VariableType', 'Object', 'ObjectType'],
    title: 'NodeTypeEnum'
} as const;

export const NodeTypePublicSchema = {
    properties: {
        create_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Create Time'
        },
        update_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Update Time'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        node_type: {
            '$ref': '#/components/schemas/NodeTypeEnum'
        }
    },
    type: 'object',
    required: ['id', 'node_type'],
    title: 'NodeTypePublic'
} as const;

export const NodesetCreateSchema = {
    properties: {
        uri: {
            type: 'string',
            minLength: 1,
            format: 'uri',
            title: 'Uri'
        },
        name_short: {
            type: 'string',
            title: 'Name Short'
        },
        version: {
            type: 'string',
            title: 'Version'
        },
        publication_date: {
            type: 'string',
            format: 'date-time',
            title: 'Publication Date'
        },
        download_url: {
            type: 'string',
            minLength: 1,
            format: 'uri',
            title: 'Download Url'
        }
    },
    type: 'object',
    required: ['uri', 'name_short', 'version', 'publication_date', 'download_url'],
    title: 'NodesetCreate'
} as const;

export const NodesetPublicSchema = {
    properties: {
        create_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Create Time'
        },
        update_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Update Time'
        },
        uri: {
            type: 'string',
            minLength: 1,
            format: 'uri',
            title: 'Uri'
        },
        name_short: {
            type: 'string',
            title: 'Name Short'
        },
        version: {
            type: 'string',
            title: 'Version'
        },
        publication_date: {
            type: 'string',
            format: 'date-time',
            title: 'Publication Date'
        },
        download_url: {
            type: 'string',
            minLength: 1,
            format: 'uri',
            title: 'Download Url'
        },
        id: {
            type: 'integer',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['uri', 'name_short', 'version', 'publication_date', 'download_url', 'id'],
    title: 'NodesetPublic'
} as const;

export const NodesetPublicWithListsSchema = {
    properties: {
        create_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Create Time'
        },
        update_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Update Time'
        },
        uri: {
            type: 'string',
            minLength: 1,
            format: 'uri',
            title: 'Uri'
        },
        name_short: {
            type: 'string',
            title: 'Name Short'
        },
        version: {
            type: 'string',
            title: 'Version'
        },
        publication_date: {
            type: 'string',
            format: 'date-time',
            title: 'Publication Date'
        },
        download_url: {
            type: 'string',
            minLength: 1,
            format: 'uri',
            title: 'Download Url'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        specs: {
            items: {
                '$ref': '#/components/schemas/SpecPublic'
            },
            type: 'array',
            title: 'Specs',
            default: []
        },
        required_nodesets: {
            items: {
                '$ref': '#/components/schemas/NodesetPublic'
            },
            type: 'array',
            title: 'Required Nodesets',
            default: []
        },
        required_by_nodesets: {
            items: {
                '$ref': '#/components/schemas/NodesetPublic'
            },
            type: 'array',
            title: 'Required By Nodesets',
            default: []
        }
    },
    type: 'object',
    required: ['uri', 'name_short', 'version', 'publication_date', 'download_url', 'id'],
    title: 'NodesetPublicWithLists'
} as const;

export const NodesetRequiredLinkCreateSchema = {
    properties: {
        nodeset_id: {
            type: 'integer',
            title: 'Nodeset Id'
        },
        required_nodeset_id: {
            type: 'integer',
            title: 'Required Nodeset Id'
        },
        is_correct_version: {
            type: 'boolean',
            title: 'Is Correct Version'
        }
    },
    type: 'object',
    required: ['nodeset_id', 'required_nodeset_id', 'is_correct_version'],
    title: 'NodesetRequiredLinkCreate'
} as const;

export const NodesetRequiredLinkPublicSchema = {
    properties: {
        create_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Create Time'
        },
        update_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Update Time'
        },
        nodeset_id: {
            type: 'integer',
            title: 'Nodeset Id'
        },
        required_nodeset_id: {
            type: 'integer',
            title: 'Required Nodeset Id'
        },
        is_correct_version: {
            type: 'boolean',
            title: 'Is Correct Version'
        }
    },
    type: 'object',
    required: ['nodeset_id', 'required_nodeset_id', 'is_correct_version'],
    title: 'NodesetRequiredLinkPublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const SpecCreateSchema = {
    properties: {
        number: {
            type: 'string',
            title: 'Number'
        },
        name_long: {
            type: 'string',
            title: 'Name Long'
        },
        name_short: {
            type: 'string',
            title: 'Name Short'
        },
        version: {
            type: 'string',
            title: 'Version'
        },
        release_date: {
            type: 'string',
            format: 'date',
            title: 'Release Date'
        },
        summary: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Summary'
        },
        summary_vector: {
            anyOf: [
                {
                    items: {
                        type: 'number'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Summary Vector'
        },
        download_url: {
            type: 'string',
            minLength: 1,
            format: 'uri',
            title: 'Download Url'
        }
    },
    type: 'object',
    required: ['number', 'name_long', 'name_short', 'version', 'release_date', 'summary', 'download_url'],
    title: 'SpecCreate'
} as const;

export const SpecNodesetLinkCreateSchema = {
    properties: {
        spec_id: {
            type: 'integer',
            title: 'Spec Id'
        },
        nodeset_id: {
            type: 'integer',
            title: 'Nodeset Id'
        },
        is_correct_version: {
            type: 'boolean',
            title: 'Is Correct Version'
        }
    },
    type: 'object',
    required: ['spec_id', 'nodeset_id', 'is_correct_version'],
    title: 'SpecNodesetLinkCreate'
} as const;

export const SpecNodesetLinkPublicSchema = {
    properties: {
        create_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Create Time'
        },
        update_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Update Time'
        },
        spec_id: {
            type: 'integer',
            title: 'Spec Id'
        },
        nodeset_id: {
            type: 'integer',
            title: 'Nodeset Id'
        },
        is_correct_version: {
            type: 'boolean',
            title: 'Is Correct Version'
        }
    },
    type: 'object',
    required: ['spec_id', 'nodeset_id', 'is_correct_version'],
    title: 'SpecNodesetLinkPublic'
} as const;

export const SpecPublicSchema = {
    properties: {
        create_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Create Time'
        },
        update_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Update Time'
        },
        number: {
            type: 'string',
            title: 'Number'
        },
        name_long: {
            type: 'string',
            title: 'Name Long'
        },
        name_short: {
            type: 'string',
            title: 'Name Short'
        },
        version: {
            type: 'string',
            title: 'Version'
        },
        release_date: {
            type: 'string',
            format: 'date',
            title: 'Release Date'
        },
        summary: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Summary'
        },
        summary_vector: {
            anyOf: [
                {
                    items: {
                        type: 'number'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Summary Vector'
        },
        download_url: {
            type: 'string',
            minLength: 1,
            format: 'uri',
            title: 'Download Url'
        },
        id: {
            type: 'integer',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['number', 'name_long', 'name_short', 'version', 'release_date', 'summary', 'download_url', 'id'],
    title: 'SpecPublic'
} as const;

export const SpecPublicWithListsSchema = {
    properties: {
        create_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Create Time'
        },
        update_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Update Time'
        },
        number: {
            type: 'string',
            title: 'Number'
        },
        name_long: {
            type: 'string',
            title: 'Name Long'
        },
        name_short: {
            type: 'string',
            title: 'Name Short'
        },
        version: {
            type: 'string',
            title: 'Version'
        },
        release_date: {
            type: 'string',
            format: 'date',
            title: 'Release Date'
        },
        summary: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Summary'
        },
        summary_vector: {
            anyOf: [
                {
                    items: {
                        type: 'number'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Summary Vector'
        },
        download_url: {
            type: 'string',
            minLength: 1,
            format: 'uri',
            title: 'Download Url'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        data_types: {
            items: {
                '$ref': '#/components/schemas/DataTypePublic'
            },
            type: 'array',
            title: 'Data Types',
            default: []
        },
        nodes: {
            items: {
                '$ref': '#/components/schemas/NodePublic'
            },
            type: 'array',
            title: 'Nodes',
            default: []
        },
        nodesets: {
            items: {
                '$ref': '#/components/schemas/NodesetPublic'
            },
            type: 'array',
            title: 'Nodesets',
            default: []
        }
    },
    type: 'object',
    required: ['number', 'name_long', 'name_short', 'version', 'release_date', 'summary', 'download_url', 'id'],
    title: 'SpecPublicWithLists'
} as const;

export const SpecSemSearchSchema = {
    properties: {
        spec: {
            '$ref': '#/components/schemas/SpecPublic'
        },
        similarity: {
            type: 'number',
            title: 'Similarity'
        }
    },
    type: 'object',
    required: ['spec', 'similarity'],
    title: 'SpecSemSearch'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UnitCreateSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        unece_code: {
            type: 'string',
            title: 'Unece Code'
        },
        display_name: {
            type: 'string',
            title: 'Display Name'
        },
        description: {
            type: 'string',
            title: 'Description'
        }
    },
    type: 'object',
    required: ['id', 'unece_code', 'display_name', 'description'],
    title: 'UnitCreate'
} as const;

export const UnitPublicSchema = {
    properties: {
        create_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Create Time'
        },
        update_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Update Time'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        unece_code: {
            type: 'string',
            title: 'Unece Code'
        },
        display_name: {
            type: 'string',
            title: 'Display Name'
        },
        description: {
            type: 'string',
            title: 'Description'
        }
    },
    type: 'object',
    required: ['id', 'unece_code', 'display_name', 'description'],
    title: 'UnitPublic'
} as const;

export const UnitPublicWithListsSchema = {
    properties: {
        create_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Create Time'
        },
        update_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Update Time'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        unece_code: {
            type: 'string',
            title: 'Unece Code'
        },
        display_name: {
            type: 'string',
            title: 'Display Name'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        nodes: {
            items: {
                '$ref': '#/components/schemas/NodesetPublic'
            },
            type: 'array',
            title: 'Nodes',
            default: []
        }
    },
    type: 'object',
    required: ['id', 'unece_code', 'display_name', 'description'],
    title: 'UnitPublicWithLists'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 40,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;