/*Copyright 2026 Fraunhofer-Gesellschaft zur Förderung der angewandten Forschung e.V. and Universität Stuttgart

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.*/


// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type DataTypeCreate = {
    expanded_node_id: string;
    display_name: string;
    definition: (string | null);
    definition_vector?: (Array<(number)> | null);
    description: (string | null);
    description_vector?: (Array<(number)> | null);
    documentation: (string | null);
    id?: (number | null);
    is_abstract: boolean;
    spec_id: number;
};

export type DataTypePublic = {
    create_time?: (string | null);
    update_time?: (string | null);
    expanded_node_id: string;
    display_name: string;
    definition: (string | null);
    definition_vector?: (Array<(number)> | null);
    description: (string | null);
    description_vector?: (Array<(number)> | null);
    documentation: (string | null);
    id?: (number | null);
    is_abstract: boolean;
    spec_id: number;
    spec: SpecPublic;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type ModellingRuleEnum = 'M' | 'O' | 'MP' | 'OP';

export type ModellingRulePublic = {
    create_time?: (string | null);
    update_time?: (string | null);
    id: number;
    rule: ModellingRuleEnum;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type NodeCreate = {
    expanded_node_id: string;
    display_name: string;
    definition: (string | null);
    definition_vector?: (Array<(number)> | null);
    description: (string | null);
    description_vector?: (Array<(number)> | null);
    documentation: (string | null);
    node_type_id: number;
    spec_id: number;
    typedefinition_id?: (number | null);
    parent_id: (number | null);
    example_id?: (number | null);
    data_type_id?: (number | null);
    unit_id?: (number | null);
    modelling_rule_id?: (number | null);
    naming_example?: (string | null);
    is_abstract?: (boolean | null);
};

export type NodePublic = {
    create_time?: (string | null);
    update_time?: (string | null);
    expanded_node_id: string;
    display_name: string;
    definition: (string | null);
    definition_vector?: (Array<(number)> | null);
    description: (string | null);
    description_vector?: (Array<(number)> | null);
    documentation: (string | null);
    node_type_id: number;
    spec_id: number;
    typedefinition_id?: (number | null);
    parent_id: (number | null);
    example_id?: (number | null);
    data_type_id?: (number | null);
    unit_id?: (number | null);
    modelling_rule_id?: (number | null);
    naming_example?: (string | null);
    is_abstract?: (boolean | null);
    id: number;
    node_type: NodeTypePublic;
    spec: SpecPublic;
    parent: (NodePublicReference | null);
    typedefinition: (NodePublicReference | null);
    data_type: (DataTypePublic | null);
    unit: (UnitPublic | null);
    modelling_rule: (ModellingRulePublic | null);
};

export type NodePublicReference = {
    create_time?: (string | null);
    update_time?: (string | null);
    expanded_node_id: string;
    display_name: string;
    definition: (string | null);
    definition_vector?: (Array<(number)> | null);
    description: (string | null);
    description_vector?: (Array<(number)> | null);
    documentation: (string | null);
    node_type_id: number;
    spec_id: number;
    typedefinition_id?: (number | null);
    parent_id: (number | null);
    example_id?: (number | null);
    data_type_id?: (number | null);
    unit_id?: (number | null);
    modelling_rule_id?: (number | null);
    naming_example?: (string | null);
    is_abstract?: (boolean | null);
    id: number;
    node_type: NodeTypePublic;
    spec: SpecPublic;
    data_type: (DataTypePublic | null);
    unit: (UnitPublic | null);
    modelling_rule: (ModellingRulePublic | null);
};

export type NodeSemSearch = {
    node: NodePublic;
    similarity: number;
};

export type NodesetCreate = {
    uri: string;
    name_short: string;
    version: string;
    publication_date: string;
    download_url: string;
};

export type NodesetPublic = {
    create_time?: (string | null);
    update_time?: (string | null);
    uri: string;
    name_short: string;
    version: string;
    publication_date: string;
    download_url: string;
    id: number;
};

export type NodesetPublicWithLists = {
    create_time?: (string | null);
    update_time?: (string | null);
    uri: string;
    name_short: string;
    version: string;
    publication_date: string;
    download_url: string;
    id: number;
    specs?: Array<SpecPublic>;
    required_nodesets?: Array<NodesetPublic>;
    required_by_nodesets?: Array<NodesetPublic>;
};

export type NodesetRequiredLinkCreate = {
    nodeset_id: number;
    required_nodeset_id: number;
    is_correct_version: boolean;
};

export type NodesetRequiredLinkPublic = {
    create_time?: (string | null);
    update_time?: (string | null);
    nodeset_id: number;
    required_nodeset_id: number;
    is_correct_version: boolean;
};

export type NodeTypeEnum = 'Variable' | 'VariableType' | 'Object' | 'ObjectType';

export type NodeTypePublic = {
    create_time?: (string | null);
    update_time?: (string | null);
    id: number;
    node_type: NodeTypeEnum;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type SpecCreate = {
    number: string;
    name_long: string;
    name_short: string;
    version: string;
    release_date: string;
    summary: (string | null);
    summary_vector?: (Array<(number)> | null);
    download_url: string;
};

export type SpecNodesetLinkCreate = {
    spec_id: number;
    nodeset_id: number;
    is_correct_version: boolean;
};

export type SpecNodesetLinkPublic = {
    create_time?: (string | null);
    update_time?: (string | null);
    spec_id: number;
    nodeset_id: number;
    is_correct_version: boolean;
};

export type SpecPublic = {
    create_time?: (string | null);
    update_time?: (string | null);
    number: string;
    name_long: string;
    name_short: string;
    version: string;
    release_date: string;
    summary: (string | null);
    summary_vector?: (Array<(number)> | null);
    download_url: string;
    id: number;
};

export type SpecPublicWithLists = {
    create_time?: (string | null);
    update_time?: (string | null);
    number: string;
    name_long: string;
    name_short: string;
    version: string;
    release_date: string;
    summary: (string | null);
    summary_vector?: (Array<(number)> | null);
    download_url: string;
    id: number;
    data_types?: Array<DataTypePublic>;
    nodes?: Array<NodePublic>;
    nodesets?: Array<NodesetPublic>;
};

export type SpecSemSearch = {
    spec: SpecPublic;
    similarity: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UnitCreate = {
    id: number;
    unece_code: string;
    display_name: string;
    description: string;
};

export type UnitPublic = {
    create_time?: (string | null);
    update_time?: (string | null);
    id: number;
    unece_code: string;
    display_name: string;
    description: string;
};

export type UnitPublicWithLists = {
    create_time?: (string | null);
    update_time?: (string | null);
    id: number;
    unece_code: string;
    display_name: string;
    description: string;
    nodes?: Array<NodesetPublic>;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type DatatypesReadDatatypesData = {
    displayName?: (string | null);
    expandedNodeId?: (string | null);
    id?: (number | null);
};

export type DatatypesReadDatatypesResponse = (Array<DataTypePublic>);

export type DatatypesCreateDatatypeData = {
    requestBody: DataTypeCreate;
};

export type DatatypesCreateDatatypeResponse = (DataTypePublic);

export type DatatypesReadDatatypeData = {
    datatypeId: number;
};

export type DatatypesReadDatatypeResponse = (DataTypePublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type ModellingRulesReadModellingRuleData = {
    modellingRuleId: number;
};

export type ModellingRulesReadModellingRuleResponse = (ModellingRulePublic);

export type NodesReadNodeData = {
    nodeId: number;
};

export type NodesReadNodeResponse = (NodePublic);

export type NodesReadNodesData = {
    displayName?: (string | null);
    expandedNodeId?: (string | null);
    id?: (number | null);
};

export type NodesReadNodesResponse = (Array<NodePublic>);

export type NodesCreateNodeData = {
    requestBody: NodeCreate;
};

export type NodesCreateNodeResponse = (NodePublic);

export type NodesSemanticSearchNodesData = {
    limit?: number;
    q: string;
    rrfK?: number;
    specId?: number;
};

export type NodesSemanticSearchNodesResponse = (Array<NodeSemSearch>);

export type NodesetsReadNodesetsData = {
    id?: (number | null);
    nameShort?: (string | null);
    publicationDate?: (string | null);
    uri?: (string | null);
    version?: (string | null);
};

export type NodesetsReadNodesetsResponse = (Array<NodesetPublicWithLists>);

export type NodesetsCreateNodesetData = {
    requestBody: NodesetCreate;
};

export type NodesetsCreateNodesetResponse = (NodesetPublic);

export type NodesetsReadNodesetData = {
    nodesetId: number;
};

export type NodesetsReadNodesetResponse = (NodesetPublicWithLists);

export type NodesetsCreateNodesetRequiredLinkData = {
    requestBody: NodesetRequiredLinkCreate;
};

export type NodesetsCreateNodesetRequiredLinkResponse = (NodesetRequiredLinkPublic);

export type NodesetsCreateSpecNodesetLinkData = {
    requestBody: SpecNodesetLinkCreate;
};

export type NodesetsCreateSpecNodesetLinkResponse = (SpecNodesetLinkPublic);

export type NodesetsGetSoloNodesetsResponse = (Array<NodesetPublicWithLists>);

export type NodesetsGetSoloSpecsResponse = (Array<SpecPublicWithLists>);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type SpecsReadSpecsData = {
    id?: (number | null);
    nameLong?: (string | null);
    nameShort?: (string | null);
    number?: (string | null);
    version?: (string | null);
};

export type SpecsReadSpecsResponse = (Array<SpecPublic>);

export type SpecsCreateSpecData = {
    requestBody: SpecCreate;
};

export type SpecsCreateSpecResponse = (SpecPublic);

export type SpecsReadSpecData = {
    specId: number;
};

export type SpecsReadSpecResponse = (SpecPublic);

export type SpecsSemanticSearchSpecsData = {
    limit?: number;
    q: string;
    rrfK?: number;
};

export type SpecsSemanticSearchSpecsResponse = (Array<SpecSemSearch>);

export type UnitsReadUnitData = {
    unitId: number;
};

export type UnitsReadUnitResponse = (UnitPublicWithLists);

export type UnitsReadUnitsData = {
    description?: (string | null);
    displayName?: (string | null);
    id?: (number | null);
};

export type UnitsReadUnitsResponse = (Array<UnitPublicWithLists>);

export type UnitsCreateUnitData = {
    requestBody: UnitCreate;
};

export type UnitsCreateUnitResponse = (UnitPublicWithLists);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);