# Copyright 2026 Fraunhofer-Gesellschaft zur Förderung der angewandten Forschung e.V. and Universität Stuttgart

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""initial

Revision ID: f06a0379d67e
Revises: 
Create Date: 2026-07-22 14:58:09.443025

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector
import app
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f06a0379d67e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modelling_rule',
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule', sa.Enum('mandatory', 'optional', 'mandatory_placeholder', 'optional_placeholder', name='modellingruleenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule')
    )
    op.create_table('node_class',
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_class', sa.Enum('variable', 'variable_type', 'object', 'object_type', 'method', 'data_type', name='nodeclassenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_class')
    )
    op.create_table('nodeset',
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('uri', app.models.UriType(length=2083), nullable=False),
    sa.Column('name_short', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('publication_date', sa.DateTime(), nullable=False),
    sa.Column('download_url', app.models.UriType(length=2083), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_short')
    )
    op.create_table('spec',
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_long', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_short', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary_vector', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('download_url', app.models.UriType(length=2083), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('nodeset_required_link',
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('nodeset_id', sa.Integer(), nullable=False),
    sa.Column('required_nodeset_id', sa.Integer(), nullable=False),
    sa.Column('is_correct_version', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['nodeset_id'], ['nodeset.id'], ),
    sa.ForeignKeyConstraint(['required_nodeset_id'], ['nodeset.id'], ),
    sa.PrimaryKeyConstraint('nodeset_id', 'required_nodeset_id')
    )
    op.create_table('nodeset_requirement_helper',
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nodeset_id', sa.Integer(), nullable=False),
    sa.Column('required_nodeset_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('required_nodeset_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['nodeset_id'], ['nodeset.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nodeset_id', 'required_nodeset_uri', 'required_nodeset_version', name='uq_nodeset_required_helper_nodeset_uri_version')
    )
    op.create_table('spec_nodeset_link',
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('spec_id', sa.Integer(), nullable=False),
    sa.Column('nodeset_id', sa.Integer(), nullable=False),
    sa.Column('is_correct_version', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['nodeset_id'], ['nodeset.id'], ),
    sa.ForeignKeyConstraint(['spec_id'], ['spec.id'], ),
    sa.PrimaryKeyConstraint('spec_id', 'nodeset_id')
    )
    op.create_table('node',
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expanded_node_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name_vector', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('definition', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('definition_vector', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description_vector', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('documentation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('node_class_id', sa.Integer(), nullable=False),
    sa.Column('spec_id', sa.Integer(), nullable=True),
    sa.Column('nodeset_id', sa.Integer(), nullable=False),
    sa.Column('typedefinition_id', sa.Integer(), nullable=True),
    sa.Column('typedefinition_expanded_node_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('parent_expanded_node_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_type_id', sa.Integer(), nullable=True),
    sa.Column('data_type_expanded_node_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('modelling_rule_id', sa.Integer(), nullable=True),
    sa.Column('is_abstract', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['data_type_id'], ['node.id'], ),
    sa.ForeignKeyConstraint(['modelling_rule_id'], ['modelling_rule.id'], ),
    sa.ForeignKeyConstraint(['node_class_id'], ['node_class.id'], ),
    sa.ForeignKeyConstraint(['nodeset_id'], ['nodeset.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['node.id'], ),
    sa.ForeignKeyConstraint(['spec_id'], ['spec.id'], ),
    sa.ForeignKeyConstraint(['typedefinition_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expanded_node_id')
    )
    op.create_index('ix_node_bm25', 'node', ['id', 'display_name', 'definition', 'description', 'documentation'], unique=False, postgresql_using='bm25', postgresql_with={'key_field': 'id'})
    op.create_index(
        "ix_node_node_class_id",
        "node",
        ["node_class_id"],
        unique=False,
    )
    op.create_index(
        "ix_node_nodeset_id",
        "node",
        ["nodeset_id"],
        unique=False,
    )


    op.execute("DROP EXTENSION IF EXISTS postgis_tiger_geocoder")
    op.execute("DROP EXTENSION IF EXISTS postgis_topology")
    op.execute("DROP EXTENSION IF EXISTS postgis_raster")
    op.execute("DROP EXTENSION IF EXISTS postgis")
    op.execute("DROP SCHEMA IF EXISTS tiger CASCADE")
    op.execute("DROP SCHEMA IF EXISTS topology CASCADE")
    op.execute("DROP TABLE IF EXISTS spatial_ref_sys")



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_typmod_cache',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('typmod', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('_typmod_cache_pkey')),
    sa.UniqueConstraint('typmod', name=op.f('_typmod_cache_typmod_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index('ix_node_bm25', table_name='node', postgresql_using='bm25', postgresql_with={'key_field': 'id'})
    op.drop_table('node')
    op.drop_table('spec_nodeset_link')
    op.drop_table('nodeset_requirement_helper')
    op.drop_table('nodeset_required_link')
    op.drop_table('spec')
    op.drop_table('nodeset')
    op.drop_table('node_class')
    op.drop_table('modelling_rule')
    # ### end Alembic commands ###
