/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSearchRouteImport } from './routes/_layout/search'
import { Route as LayoutMetricsGraphRouteImport } from './routes/_layout/metrics-graph'
import { Route as LayoutLintingRouteImport } from './routes/_layout/linting'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSearchRoute = LayoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMetricsGraphRoute = LayoutMetricsGraphRouteImport.update({
  id: '/metrics-graph',
  path: '/metrics-graph',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLintingRoute = LayoutLintingRouteImport.update({
  id: '/linting',
  path: '/linting',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/linting': typeof LayoutLintingRoute
  '/metrics-graph': typeof LayoutMetricsGraphRoute
  '/search': typeof LayoutSearchRoute
}
export interface FileRoutesByTo {
  '/linting': typeof LayoutLintingRoute
  '/metrics-graph': typeof LayoutMetricsGraphRoute
  '/search': typeof LayoutSearchRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/linting': typeof LayoutLintingRoute
  '/_layout/metrics-graph': typeof LayoutMetricsGraphRoute
  '/_layout/search': typeof LayoutSearchRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/linting' | '/metrics-graph' | '/search'
  fileRoutesByTo: FileRoutesByTo
  to: '/linting' | '/metrics-graph' | '/search' | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/linting'
    | '/_layout/metrics-graph'
    | '/_layout/search'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/search': {
      id: '/_layout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof LayoutSearchRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/metrics-graph': {
      id: '/_layout/metrics-graph'
      path: '/metrics-graph'
      fullPath: '/metrics-graph'
      preLoaderRoute: typeof LayoutMetricsGraphRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/linting': {
      id: '/_layout/linting'
      path: '/linting'
      fullPath: '/linting'
      preLoaderRoute: typeof LayoutLintingRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutLintingRoute: typeof LayoutLintingRoute
  LayoutMetricsGraphRoute: typeof LayoutMetricsGraphRoute
  LayoutSearchRoute: typeof LayoutSearchRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutLintingRoute: LayoutLintingRoute,
  LayoutMetricsGraphRoute: LayoutMetricsGraphRoute,
  LayoutSearchRoute: LayoutSearchRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
